#!/usr/bin/env php
<?php

use App\Recurrence\RecurringService;

require dirname(__DIR__).'/vendor/autoload.php';

$service = new RecurringService();
$recurrence = $service->getRecurrence('weekly');

$baseTimestamp = new DateTimeImmutable("2023-05-07 8:30");
$now = new DateTimeImmutable();
$now = new DateTimeImmutable("2023-05-08 8:20");
$lastEventTimestamp = new DateTimeImmutable("2023-05-10 8:00");
$timestamp = $recurrence->getNextTimestamp($baseTimestamp, $now, $lastEventTimestamp);
var_dump($timestamp);
