#!/usr/bin/env php
<?php

use App\Recurrence\RecurrenceService;

require dirname(__DIR__).'/vendor/autoload.php';

$service = new RecurringService();
$recurrence = $service->getRecurrence('weekly');

$baseTimestamp = new DateTimeImmutable("2023-05-01 8:00");
$now = new DateTimeImmutable();
$lastEventTimestamp = new DateTimeImmutable("2023-05-27 8:00");

$timestamp = $recurrence->getNextTimestamp($baseTimestamp, $now, $lastEventTimestamp);
$timestamp = $recurrence->getNextTimestamp($baseTimestamp, $now, $lastEventTimestamp);
var_dump($timestamp);
